name: Build, Push and Deploy a Docker Image

# [X] Build droplet 
# [X] Build container image 
# [X] Push to registry (DO)
# [ ] Deploy to droplet
# [ ] Run

on:
    push:
      branches: [main]

env:
    DO_TOKEN: "${{ secrets.DO_TOKEN }}"

jobs:
 build-droplet:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Generate SSH Key
       run: |
         ssh-keygen -t rsa -b 4096 -f /tmp/id_rsa -N ""
         echo "SSH_PRIVATE_KEY=$(cat /tmp/id_rsa)" >> $GITHUB_ENV
         echo "SSH_PUBLIC_KEY=$(cat /tmp/id_rsa.pub)" >> $GITHUB_ENV
         echo "ssh_key_path=/tmp/id_rsa" >> $GITHUB_ENV
        
     - name: Install Terraform
       uses: hashicorp/setup-terraform@v3
       with:
        terraform_version: 1.10.2
    
     - name: Set D_O S3Var
       run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.DO_SPACES_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.DO_SPACES_SECRET_KEY }}" >> $GITHUB_ENV
       
     - name: Terraform Init
       run: terraform init
       working-directory: ./terraform
       env:
        DO_TOKEN: ${{ secrets.DO_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET_KEY }}

     - name: Terraform Apply
       id: apply
       run: terraform apply -auto-approve -var "do_token=${{ secrets.DO_TOKEN }}"
       working-directory: ./terraform
       env:
        DO_TOKEN: ${{ secrets.DO_TOKEN }}

     - name: Get Droplet Outputs
       id: outputs
       run: |
        echo "id=$(terraform output -raw droplet_info.id)" >> $GITHUB_ENV
        echo "name=$(terraform output -raw droplet_info.name)" >> $GITHUB_ENV
        echo "ipv4=$(terraform output -raw droplet_info.ipv4)" >> $GITHUB_ENV

     - name: Validate Droplet Info
       run: |
        echo "Droplet ID: $id"
        echo "Droplet Name: $name"
        echo "Droplet IP: $ipv4"
  
 build_and_push: 
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build container image 
      run: docker build -t hello-world .   

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_TOKEN }}  

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600        
    
    - name: Tag image 
      run: docker tag hello-world registry.digitalocean.com/my-container-reg/hello-world
      # docker tag <my-image> registry.digitalocean.com/<my-registry>/<my-image>

    - name: Push image to DO Container Registry 
      run: docker push registry.digitalocean.com/my-container-reg/hello-world
      # docker push registry.digitalocean.com/<my-registry>/<my-image>
 
 deploy: 
   runs-on: ubuntu-latest
   needs: build_and_push 

   steps:
    - name: Checkout repository
      uses: actions/checkout@v4  

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_TOKEN }}  

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600 

