name: Build, Push and Deploy a Docker Image

# [X] Build droplet 
# [X] Build container image 
# [X] Push to registry (DO)
# [ ] Deploy to droplet
# [ ] Run

on:
    push:
      branches: [main]

env:
    DO_TOKEN: "${{ secrets.DO_TOKEN }}"

jobs:
 build_droplet:
   runs-on: ubuntu-latest
   outputs:
    id: ${{ steps.dropletOutputs.outputs.id}}
    ipv4: ${{ steps.dropletOutputs.outputs.ipv4}}
    name: ${{ steps.dropletOutputs.outputs.name}}

   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
        
     - name: Install Terraform
       uses: hashicorp/setup-terraform@v3
       with:
        terraform_version: 1.10.2
    
     - name: Set D_O S3Var
       run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.DO_SPACES_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.DO_SPACES_SECRET_KEY }}" >> $GITHUB_ENV
       
     - name: Terraform Init
       run: terraform init
       working-directory: ./terraform
       env:
        DO_TOKEN: ${{ secrets.DO_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET_KEY }}

     - name: Terraform Apply
       id: apply
       run: |
         terraform apply -auto-approve \
          -var "do_token=${{ secrets.DO_TOKEN }}" \
          -var "public_key=${{ secrets.DO_SSH_PUBLIC_KEY }}"
       working-directory: ./terraform
       env:
        DO_TOKEN: ${{ secrets.DO_TOKEN }}
      
     - name: Get Droplet Outputs
       id: dropletOutputs
       run: |
        DROPLET_INFO=$(terraform output -json droplet_info)
        echo "id=$(echo $DROPLET_INFO | jq -r '.id')" >> $GITHUB_OUTPUT
        echo "ipv4=$(echo $DROPLET_INFO | jq -r '.ipv4')" >> $GITHUB_OUTPUT
        echo "name=$(echo $DROPLET_INFO | jq -r '.name')" >> $GITHUB_OUTPUT
       working-directory: ./terraform  

     - name: Validate Droplet Info
       run: |
        echo "Droplet ID: $id"
        echo "Droplet Name: $name"
        echo "Droplet IP: $ipv4"
  
 build_and_push: 
  runs-on: ubuntu-latest
  needs: build_droplet
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build container image 
      run: docker build -t hello-world .   

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_TOKEN }}  

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600        
    
    - name: Tag image 
      run: docker tag hello-world registry.digitalocean.com/my-container-reg/hello-world
      # docker tag <my-image> registry.digitalocean.com/<my-registry>/<my-image>

    - name: Push image to DO Container Registry 
      run: docker push registry.digitalocean.com/my-container-reg/hello-world
      # docker push registry.digitalocean.com/<my-registry>/<my-image>
 
 deploy: 
   runs-on: ubuntu-latest
   needs: 
    - build_droplet
    - build_and_push

   steps:
    - name: Checkout repository
      uses: actions/checkout@v4  

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_TOKEN }}  

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600 

    - name: Deploy to Droplet via SSH Action
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ needs.build_droplet.outputs.ipv4 }}
        username: root
        key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        
        script: |

            # Update packages 
            sudo apt-get update
            # install Docker 
            sudo apt install docker.io -y 
            # Stop running container
            docker stop hello-world

            # Remove old container
            docker rm hello-world

            # Login to registry
            docker login -u ${{ secrets.DO_TOKEN }} -p ${{ secrets.DO_TOKEN }} registry.digitalocean.com

            # Run a new container from a new image
            docker run -d \
            --restart always \
            -p 4001:4000 \
            --name hello-world \
            registry.digitalocean.com/my-container-reg/hello-world